MG1933072
idiomaticrefactoring/sehomework pull request #134
Opened 2019-11-25 14:39 UTC by JiaxinTse

MG1933072 谢佳鑫

2019-11-25 14:51 UTC, ganyz commented
DZ1633005 甘元柱 评估已通过

2019-11-27 14:15 UTC, zjzh commented on MG1933072/java/ArrayList_listIterator_int.java
> +     * ArrayList$class0-ArrayList$ArrayList();ArrayList$add(e) & e="I" & https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html
add(e) e缺少类型

2019-11-27 14:18 UTC, zjzh commented on MG1933072/java/FileOutputStream_close.java
> +     */
两个class

2019-11-27 14:19 UTC, zjzh commented on MG1933072/java/LinkedList_listIterator_int.java
> +     */
ret0删去

2019-11-27 14:21 UTC, idiomaticrefactoring requested changes
good

2019-11-28 14:39 UTC, closed without merging