MG1933053 陶光品
idiomaticrefactoring/sehomework pull request #135
Opened 2019-11-26 05:44 UTC by Gptao

ArrayList,102 same
PrintStream,134 same (OutputStream$write map,String$write nomap)
Calendar,50 same
File,142 same same
String,50 same same
PrintStream,6 same (no map)

2019-11-26 06:49 UTC, starry-xin commented
MG1933054 田鑫 评估已通过

2019-11-27 14:09 UTC, merged

2019-11-27 14:11 UTC, zjzh commented on MG1933053/java/Calendar_set_int_int_int_int_int.java
> +     * class0: Calendar$class0
去掉：

2019-11-27 14:11 UTC, zjzh commented on MG1933053/java/PrintStream_print_Array.java
> +     */
OutputStream$out 或者直接out

2019-11-27 14:13 UTC, idiomaticrefactoring requested changes
perfect-2