MF1933120_张晓雯
idiomaticrefactoring/sehomework pull request #141
Opened 2019-11-26 13:58 UTC by wwxxzz

1. Collections,58 same
2. File,26 same
3. LinkedList,158 same
4. Arrays,30 same
5. Integer,10 same

2019-11-26 14:09 UTC, ZhangSheng1101 commented
MF1933119 张胜 评估已通过

2019-11-27 14:27 UTC, zjzh commented on MF1933120/java/Collection_disjoint_Collection_Collection.java
> +     * collection1 Collection$collection1
变量名

2019-11-27 14:28 UTC, zjzh commented on MF1933120/java/File_setWritable_Boolean.java
> +     * writable0 writable0=true
变量名，参考群文件

2019-11-27 14:29 UTC, zjzh commented on MF1933120/swift/Array_append_Element.swift
> +     * output: 0
这个class0直接赋值

2019-11-27 14:30 UTC, idiomaticrefactoring requested changes
OK

2019-11-28 03:10 UTC, closed without merging