MF1933072
idiomaticrefactoring/sehomework pull request #155
Opened 2019-11-27 09:41 UTC by Yudezhi

Integer,100 same
Throwable,6 same
Class,98 same
FileInputStream,26 same
LinkedList,6 same
---
主要根据评论以及参考相关文档按照自己理解进行了更改。主要的修改集中再对于“&”的格式要求和“class0”的理解。

2019-11-27 09:55 UTC, Tomlk commented
MF1933067 龙坤 评估已通过

2019-11-27 11:48 UTC, zjzh commented on MF1933072/java/Class_getMethods.java
> +
断言？正常的需要返回一个长度不为0的数组

2019-11-27 11:50 UTC, zjzh commented on MF1933072/java/Integer_compare_int_int.java
> +     */
去掉class0

2019-11-27 11:51 UTC, zjzh commented on MF1933072/java/LinkedList_element.java
> +     */
去掉<>

2019-11-27 11:59 UTC, zjzh commented on MF1933072/swift/NSError_localizedDescription.swift
> +     */
class0的数据类型

2019-11-27 12:00 UTC, zjzh commented on MF1933072/swift/NSNumber_compare_NSNumber.swift
> +
命名

2019-11-27 12:07 UTC, zjzh commented on MF1933072/swift/Objective-C Runtime_class_copyMethodList_Class_int.swift
> +        }
这个代码编译不出错？

2019-11-27 12:07 UTC, idiomaticrefactoring requested changes
good

2019-11-27 13:06 UTC, Yudezhi commented on MF1933072/swift/Objective-C Runtime_class_copyMethodList_Class_int.swift
> +        }
不知道，参考网上写法，没有mac，runtime Windows上跑不出来

2019-11-29 02:31 UTC, Yudezhi commented on MF1933072/java/Integer_compare_int_int.java
> +     */
关于变量命名，我看了您发的所有的文件，实在没找出问题。。。

2019-11-29 02:52 UTC, Yudezhi commented on MF1933072/swift/NSError_localizedDescription.swift
> +     */
自定义的枚举类型，那我就加上了。

2019-11-29 09:29 UTC, closed without merging