MF1933041_江彪
idiomaticrefactoring/sehomework pull request #18
Opened 2019-11-12 14:20 UTC by sinat-biao

# 第一次提交
包含所有 api 代码（v1.0）

2019-11-13 15:49 UTC, zjzh commented on MF1933041/java/ArrayList_addAll_int_ArrayList.java
> +}
变量初始化

2019-11-20 02:40 UTC, zjzh commented on MF1933041/java/ArrayList_addAll_int_ArrayList.java
> +     */
缺少return的值

2019-11-20 02:43 UTC, zjzh commented on MF1933041/java/LinkedList_add_Object.java
> +     * LinkedList$class0-LinkedList$LinkedList<Object>() & https://docs.oracle.com/javase/8/docs/api/
两个&

2019-11-20 02:43 UTC, zjzh commented on MF1933041/java/LinkedList_add_Object.java
> +    @Test
这里的ret0输出是确定的

2019-11-20 02:44 UTC, zjzh commented on MF1933041/java/String_valueOf_double.java
> +     * Double$class0-Double$Double(double value) & Double$double=123 & https://docs.oracle.com/javase/8/docs/api/
value=123

2019-11-20 02:46 UTC, zjzh commented on MF1933041/swift/ArrayList/ArraySlice_insert_ArraySlice.swift
> +     */
class1 命名错误

2019-11-20 02:47 UTC, zjzh commented on MF1933041/swift/ArrayList/Array_insert_Array.swift
> +Array_insert_Array.insert2()
api的使用和注释api不一致

2019-11-20 02:51 UTC, zjzh commented on MF1933041/swift/Integer/Process_processInfo$ProcessInfo_environment$Dictionary__String.swift
> + */
@Map 以及这个代码有点奇怪

2019-11-20 02:53 UTC, idiomaticrefactoring requested changes
good

2019-11-26 02:23 UTC, webprogra commented on MF1933041/java/ArrayList_addAll_int_ArrayList.java
> +        boolean ret0 = class0.addAll(0, class1);
这里的0可以用变量表示，然后将变量加到方法前的input里

2019-11-26 02:24 UTC, webprogra commented on MF1933041/java/HashMap_clear.java
> + * @className: HashMap_clear_
className多了一个下划线

2019-11-26 02:35 UTC, webprogra commented on MF1933041/java/Integer_getInteger_String.java
> +     * class0 class0="sun.arch.data.model"
这里的class0是不是应该与Integer有关，string类型应该只是其中的一个输入

2019-11-26 02:45 UTC, webprogra commented on MF1933041/java/String_valueOf_double.java
> +     * class0 Double$class0
这里的class0是不是也应该与String相关，double类型应该只是形参变量名

2019-11-26 02:45 UTC, webprogra commented on MF1933041/java/String_valueOf_double.java
> +     * class0 Double$class0
下面的同理

2019-11-26 02:50 UTC, webprogra commented on MF1933041/swift/ArrayList/Array_insert_Array.swift
> +		let i = 0
这里的缩进

2019-11-26 02:54 UTC, webprogra commented on MF1933041/swift/HashMap/NSMapTable_removeAllObjects_.swift
> +     * rob Person$rob
这里应该只有这个方法的形参的初始化，所以person类的初始化可以写下面class0的初始化中

2019-11-26 03:01 UTC, webprogra commented on MF1933041/swift/Integer/NSString_integerValue_String.swift
> +		assert(ret0 == 1357)
缩进

2019-11-26 03:03 UTC, webprogra commented on MF1933041/swift/LinkedList/ArraySlice_append_Element.swift
> +		print(">>>>>>>>>>>>")
缩进

2019-11-26 03:04 UTC, webprogra commented on MF1933041/swift/LinkedList/ArraySlice_append_Element.swift
> +		print(">>>>>>>>>>>>")
下面同理

2019-11-26 03:12 UTC, webprogra commented on MF1933041/swift/String/String_init_double.swift
> +     * class0 class0=2.0
还有这里的class0的定义也有些问题

2019-11-26 12:30 UTC, closed without merging