MF1933067 3problems
idiomaticrefactoring/sehomework pull request #19
Opened 2019-11-12 14:21 UTC by Tomlk

2019-11-13 15:49 UTC, zjzh commented on MF1933067_3problems/java/ArrayList_size.java
> +     * ArrayList$class0-ArrayList$ArrayList();ArrayList$class0-add(int a)
link

2019-11-13 15:50 UTC, zjzh commented on MF1933067_3problems/java/PrintStream_print_double.java
> +     *PrintStream$ class0-PrintStream$PrintStream(String pathname);String$pathname="file.txt"
&分开，link

2019-11-13 15:50 UTC, zjzh commented on MF1933067_3problems/swift/ArraySlice_count.swift
> +     * class0 ArraySlice$class0
class0 pattern

2019-11-13 15:52 UTC, zjzh commented on MF1933067/java/ArrayList_size.java
> +     */
link 以及例子

2019-11-13 15:53 UTC, zjzh commented on MF1933067/java/File_lastModified.java
> +     */
link和例子 下面同样问题

2019-11-13 15:53 UTC, zjzh commented on MF1933067/java/PrintStream_print_double.java
> +     *PrintStream$ class0-PrintStream$PrintStream(String pathname);String$pathname="file.txt"
&分开，link

2019-11-20 02:54 UTC, zjzh commented on MF1933067/java/ArrayList_size.java
> +     */
缺少link以及依旧有问题

2019-11-20 02:55 UTC, zjzh commented on MF1933067/java/PrintStream_print_double.java
> +     *PrintStream$ class0-PrintStream$PrintStream(String pathname);String$pathname="file.txt"
这里是两个& 参照公告代码

2019-11-20 02:56 UTC, zjzh commented on MF1933067/swift/NSString_compare_String.swift
> +NSString_compare_String.compare0()
缺少assert,以及ret0值不对

2019-11-20 02:56 UTC, zjzh commented on MF1933067/swift/NSString_compare_String_options.swift
> +NSString_compare_String_options.compare0()
错误依旧

2019-11-20 02:57 UTC, zjzh commented on MF1933067/swift/String_init_BinaryInteger_Int_Bool.swift
> +
再次确认下结果

2019-11-20 03:06 UTC, Tomlk commented on MF1933067/java/ArrayList_size.java
> +     */
还没上传最新版本

2019-11-20 03:07 UTC, Tomlk commented on MF1933067/swift/String_init_BinaryInteger_Int_Bool.swift
> +
这不是最新代码。。。下午上传最后版本

2019-11-20 11:37 UTC, zjzh commented on MF1933067/swift/ArraySlice_count.swift
> +ArraySlice_count.count0();
class0初始化

2019-11-20 11:37 UTC, zjzh commented on MF1933067/swift/Array_count.swift
> +     */
class0初始化

2019-11-20 11:37 UTC, zjzh commented on MF1933067/swift/ContiguousArray_count.swift
> +    static func count0(){
class0初始化

2019-11-20 11:38 UTC, zjzh commented on MF1933067/swift/NSString_compare_String.swift
> +}
class0初始化 assert

2019-11-20 11:38 UTC, zjzh commented on MF1933067/swift/NSString_compare_String_options_range.swift
> +     */
ret0错误

2019-11-20 11:39 UTC, zjzh commented on MF1933067/swift/NSString_compare_String_options_range_local.swift
> +NSString_compare_String_options_range_local.compare0()
同上

2019-11-20 11:41 UTC, zjzh commented on MF1933067/swift/String_write_inOutTarget.swift
> +String_write_inOutTarget.write0();
程序再检查

2019-11-20 11:46 UTC, zjzh commented on MF1933067/swift/TextOutputStream_write_String.swift
> +TextOutputStream_write_String.write0();
再次确认代码正确性和java api的对应性

2019-11-20 12:02 UTC, zjzh commented on MF1933067/swift/main.swift
> +String_write_inOutTarget.write0();
冗余的删去

2019-11-20 12:02 UTC, zjzh commented on MF1933067/swift/URL_resourceValues.swift
> +URL_resourceValues.contentModificationDate0();
同样问题

2019-11-20 12:03 UTC, idiomaticrefactoring requested changes
ok-3

2019-11-20 13:33 UTC, zjzh commented on MF1933067/java/ArrayList_size.java
> +     */
少&，一个变量放在一块

2019-11-20 13:33 UTC, zjzh commented on MF1933067/java/File_lastModified.java
> +     */
同上面的问题

2019-11-20 13:34 UTC, zjzh commented on MF1933067/swift/Array_count.swift
> +     */
初始化在哪里

2019-11-20 13:35 UTC, idiomaticrefactoring requested changes
ok+1

2019-11-26 08:33 UTC, closed without merging