完成
idiomaticrefactoring/sehomework pull request #2
Opened 2019-11-12 01:16 UTC by CbcWestwolf

2019-11-14 00:19 UTC, zjzh commented on MG1933002/java/Calendar_set_int_int_int.java
> +     */
变量初始化

2019-11-14 00:19 UTC, zjzh commented on MG1933002/java/File_equals_Object.java
> +    */
变量初始化

2019-11-14 00:20 UTC, zjzh commented on MG1933002/swift/NSRegularExpression_replaceMatches_NSMutableString_NSRegularExpression$MatchingOptions_NSRange_String.swift
> +    */
变量初始化，和前面存在同样问题，后面也存在

2019-11-14 00:20 UTC, idiomaticrefactoring requested changes
good

2019-11-14 03:08 UTC, CbcWestwolf commented
已修正函数注释

2019-11-19 06:53 UTC, CbcWestwolf commented
String,2 same
Calendar,86 same
Integer,34 same
Integer,166 same
File,38 same

2019-11-20 00:21 UTC, zjzh commented on MG1933002/java/File_equals_Object.java
> +    */
变量命名，input个数

2019-11-20 00:24 UTC, zjzh commented on MG1933002/java/String_replaceAll_String_String.java
> +}
input个数

2019-11-20 00:26 UTC, zjzh commented on MG1933002/swift/DateComponents_init_Int_Int_Int.swift
> +DateComponents_init_Int_Int_Int.init1()
ret0有问题，可以将这个输出另起一个名字但不是 ret0

2019-11-20 00:30 UTC, idiomaticrefactoring requested changes
good

2019-11-26 13:17 UTC, vectoroverflow commented
MG1833088 张哲成 评估已通过

2019-11-28 01:16 UTC, idiomaticrefactoring approved these changes
perfect

2019-11-28 01:16 UTC, merged