finish homework, 2 API
idiomaticrefactoring/sehomework pull request #22
Opened 2019-11-12 15:15 UTC by Hao-Kailong

2019-11-13 15:35 UTC, zjzh commented on MF1933030/swift/Array_contains_Element.swift
> +Array_contains_Element.contains1()
与java测试用例不同

2019-11-13 15:35 UTC, zjzh commented on MF1933030/swift/String_write_Target.swift
> +String_write_Target.write0()
再次确认这个是不是真正的映射，并找到真正的映射

2019-11-20 08:23 UTC, koala-222 reviewed
1.PrintStream映射String.write为no，OutputStream为yes
2.Calendar映射NSCalendar为no，添加新的映射Calendar.identifier

2019-11-20 08:24 UTC, koala-222 reviewed
ArrayList,82 same
PrintStream,90 change
HashMap,82 same
Calendar,110 change
InputStream,6 same

2019-11-21 10:01 UTC, zjzh commented on MF1933030/java/ArrayList_contains_Object.java
> +     *  ArrayList$class0-ArrayList$ArrayList(Collection<? extends E> c)&c=Arrays$asList&https://www.cnblogs.com/pcheng/p/9897596.html
api在第一个&前面，可看mg1933085

2019-11-21 10:01 UTC, zjzh commented on MF1933030/java/Calendar_getCalendarType.java
> +     *  Calendar$class0-Calendar$getInstance&https://blog.csdn.net/joyous/article/details/9630893
少&

2019-11-21 10:02 UTC, zjzh commented on MF1933030/java/HashMap_keySet.java
> +     *  HashSet$ret0-HashSet$HashSet&https://blog.csdn.net/hebeiqiaozhonghui/article/details/87694587
问题同上

2019-11-21 10:04 UTC, zjzh commented on MF1933030/swift/Dictionary_keys.swift
> +     *  Dictionary<String, String>$Keys-$Dictionary$keys&https://www.jianshu.com/p/67a0cf4dad2d
再次确定ret0的类型

2019-11-21 10:04 UTC, zjzh commented on MF1933030/swift/OutputStream_write_UnsafePointer_Int.swift
> +     */
两个&

2019-11-21 10:05 UTC, zjzh commented on MF1933030/swift/Stream_close.swift
> +     */
格式错误

2019-11-21 10:05 UTC, idiomaticrefactoring requested changes
good

2019-11-27 06:15 UTC, closed without merging