MF1933121_张馨月_作业4
idiomaticrefactoring/sehomework pull request #31
Opened 2019-11-13 05:45 UTC by zhangxy-97

> <

2019-11-13 15:18 UTC, zjzh commented on MF1933121/Java/File_getCanonicalPath.java
> +    * */
变量初始化问题，下面同样

2019-11-19 08:27 UTC, zhangxy-97 commented
**File, 134 same**
Java: File_getCanonicalPath.java
Swift: URLResourceValues_canonicalPath.swift

**Thread, 30 same** 
Java: Thread_interrupt.java
Swift: Thread_exit.swift

**LinkedList, 130 same**
Java: LinkedList_getLast.java
Swift: ArraySlice_last.swift
Swift: Array_last.swift
Swift: ContiguousArray_last.swift

**HashSet, 50 same**
Java: HashSet_isEmpty.java
Swift: Set_isEmpty.swift

**String, 82 same**
Java: String_format_Locale_String_Object.java
Swift: NSString_init_String_Any_arguments.swift

2019-11-19 08:32 UTC, zhangxy-97 commented on MF1933121/Java/File_getCanonicalPath.java
> +    * */
变量初始化问题已修改，并提交剩余三种API映射～

2019-11-20 12:09 UTC, zjzh commented on MF1933121/Java/String_format_Locale_String_Object.java
> +        * */
locale形式

2019-11-20 12:10 UTC, zjzh commented on MF1933121/Java/Thread_interrupt.java
> +        class0.start();
为什么要继承

2019-11-20 12:12 UTC, zjzh commented on MF1933121/Swift/ArraySlice_last.swift
> +     */
class0

2019-11-20 12:16 UTC, zjzh commented on MF1933121/Swift/Set_isEmpty.swift
> +     Set$class0-Set$Set<Int>() & class0 = [1,2,3,4,5,6] & https://developer.apple.com/documentation/swift/set/3018383-isempty
去掉多余的class0

2019-11-20 12:17 UTC, zjzh commented on MF1933121/Swift/Set_isEmpty.swift
> +    static func isEmpty1(){
去掉多余classs0

2019-11-20 12:17 UTC, zjzh commented on MF1933121/Swift/Thread_exit.swift
> +Thread_exit.exit0()
class0  以及最后一行错误

2019-11-20 12:18 UTC, zjzh commented on MF1933121/Swift/URLResourceValues_canonicalPath.swift
> +
去掉class0=

2019-11-20 12:18 UTC, idiomaticrefactoring requested changes
good

2019-11-20 13:45 UTC, zhangxy-97 commented on MF1933121/Java/Thread_interrupt.java
> +        class0.start();
Java提供了三种创建线程的方法，分别为：

- 通过实现Runnable接口；

- 通过继承Thread类本身；

- 通过 Callable 和 Future 创建线程。
因为要映射的Java API属于Thread类，所以就选择了继承方式。

2019-11-22 08:49 UTC, closed without merging