Add files via upload
idiomaticrefactoring/sehomework pull request #39
Opened 2019-11-13 07:04 UTC by Blbert

2019-11-13 14:49 UTC, zjzh commented on MG1833064/java/Calendar_getTimeZone.java
> +     */
class0,以及ret0

2019-11-13 14:49 UTC, zjzh commented on MG1833064/java/PrintStream_close.java
> +     */
变量初始化

2019-11-13 14:50 UTC, zjzh commented on MG1833064/swift/Calendar_timeZone.swift
> + Calendar_timeZone.timeZone0()
assert语句？ 方法的注释不规范

2019-11-13 14:50 UTC, zjzh commented on MG1833064/swift/DateComponents_timeZone.swift
> + }
方法注释不规范，assert

2019-11-13 14:51 UTC, zjzh commented on MG1833064/swift/NSCalendar_timeZone.swift
> + Calendar_timeZone.timeZone0()
方法注释，assert,类名，下面同样问题

2019-11-20 12:58 UTC, zjzh commented on MG1833064/java/Calendar_getTimeZone.java
> + *  @Map: DateComponents$var timeZone: TimeZone? { get set } & NSCalendar$var timeZone: TimeZone { get set } & NSDateComponents$var timeZone: TimeZone? { get set } & Calendar$var timeZone: TimeZone {
@Map重复多次

2019-11-20 12:59 UTC, zjzh commented on MG1833064/java/Calendar_getTimeZone.java
> +     */
变量初始化错误

2019-11-20 13:00 UTC, zjzh commented on MG1833064/java/HashMap_get_Object.java
> +     */
变量初始化错误

2019-11-20 13:03 UTC, zjzh commented on MG1833064/java/HashSet_add_Object.java
> +     */
变量初始化问题后面一样

2019-11-20 13:04 UTC, idiomaticrefactoring requested changes
太多问题
ok-2

2019-11-28 02:42 UTC, shaneshbi commented
MG 1833001 毕胜 评审已通过

2020-05-19 07:01 UTC, closed without merging