MF1933116
idiomaticrefactoring/sehomework pull request #47
Opened 2019-11-13 08:52 UTC by GCCAT

2019-11-13 12:40 UTC, zjzh commented on MF1933116/java/HashMap_size.java
> +     * input: 0
缺少输入 且命名为class0

2019-11-13 12:41 UTC, zjzh commented on MF1933116/java/HashMap_forEach_action.java
> +     * input: 0
缺少输入

2019-11-13 12:42 UTC, zjzh commented on MF1933116/java/HashMap_forEach_action.java
> +    public class HashMap_forEach_action {
类名后 形参类型应该为BiConsumer

2019-11-13 12:43 UTC, zjzh commented on MF1933116/swift/Dictionary_count.swift
> +*/
测试用例缺少输入

2019-11-13 12:43 UTC, zjzh commented on MF1933116/swift/Dictionary_forEach_body.swift
> +
测试用例缺少输入

2019-11-20 15:39 UTC, zjzh commented on MF1933116/java/Collections_max_Collection.java
> +	 */
class0的初始化

2019-11-20 15:39 UTC, zjzh commented on MF1933116/java/File_canWrite.java
> +	     */
缺少& link

2019-11-20 15:40 UTC, zjzh commented on MF1933116/java/HashMap_forEach_BiConsumer.java
> +    public static int count0 = 0;
class0初始

2019-11-20 15:42 UTC, zjzh commented on MF1933116/swift/NSMapTable_count.swift
> +     */
初始化

2019-11-20 15:42 UTC, idiomaticrefactoring requested changes
good

2019-11-27 09:32 UTC, GCCAT commented
all改完~

2019-11-27 09:32 UTC, closed without merging