MF1933016
idiomaticrefactoring/sehomework pull request #52
Opened 2019-11-13 10:46 UTC by joker-ht

2019-11-13 10:52 UTC, zjzh commented on Arrays_copyOfRange_Arrays
> +public class Arrays_copyOfRange_Arrays{
类名定义错误

2019-11-13 10:56 UTC, zjzh commented on Arrays_copyOfRange_Arrays
> +   * class0 class0 []={1,2,3,4,5}
class0后面不能有[]

2019-11-13 10:59 UTC, zjzh commented on Arrays_prefix_Arrays
> +   *@className: Arrays_prefix_Arrays
类名定义错误

2019-11-13 11:00 UTC, zjzh commented on Arrays_prefix_Arrays
> +     * int int1=3
变量名定义错误

2019-11-13 11:03 UTC, zjzh commented on Arrays_prefix_Arrays
> +        print(ret2);
代码不可运行！！！！下面同理

2019-11-13 11:04 UTC, zjzh commented on NSString_substring_String
> +/**类名_方法名(_形参类型)*
类名定义，代码运行

2019-11-13 11:13 UTC, zjzh commented on String_prefix_String$NSString_substring_String
> +/**类名_方法名(_形参类型)
类名定义，不可运行

2019-11-13 11:20 UTC, zjzh commented on String_substringString
> +   *@className: String_substringString
类名形参名定义错误

2019-11-20 14:01 UTC, zjzh commented on Arrays_copyOfRange_int_int
> +*/
多余test

2019-11-20 14:03 UTC, zjzh commented on FileOutputStream_init_string_bool
> + * @Map: swift.io.OutputStream$init?(toFileAtPath path: String, append shouldAppend: Bool)
swift.io?

2019-11-20 14:04 UTC, zjzh commented on NSString_substring_int__NSString_substring_int
> +class NSString_substring_int$NSString_substring_int{
$?

2019-11-20 14:12 UTC, zjzh commented on String_prefix_String__NSString_substring_int
> +     *through String.Index$through
through初始化

2019-11-20 14:12 UTC, idiomaticrefactoring requested changes
good-1

2019-11-27 11:22 UTC, joker-ht commented
互评的同学好像不在

2019-11-27 12:51 UTC, closed without merging