MF1933002
idiomaticrefactoring/sehomework pull request #55
Opened 2019-11-13 11:17 UTC by caokangx

2019-11-13 14:13 UTC, zjzh commented on MF1933002/java/Math_max_Integer.java
> + * @Map: func max<T>(class0: T, class1: T) -> T where T : Comparable
@Map 类名缺失

2019-11-13 14:13 UTC, zjzh commented on MF1933002/java/Math_max_Integer.java
> + * @className: Math_max_Integer
类名错误

2019-11-13 14:14 UTC, zjzh commented on MF1933002/java/Math_max_Integer.java
> +     */
ret错误

2019-11-13 15:39 UTC, caokangx commented on MF1933002/java/Math_max_Integer.java
> + * @Map: func max<T>(class0: T, class1: T) -> T where T : Comparable
这是一个全局函数，不是方法

2019-11-21 05:55 UTC, zjzh commented on MF1933002/java/HashMap_remove_Object.java
> +
变量名

2019-11-21 05:56 UTC, zjzh commented on MF1933002/swift/NSMapTable_removeObject_KeyType.swift
> +    static func removeObject0(){
变量错误后面同样问题

2019-11-21 05:56 UTC, idiomaticrefactoring requested changes
ok-1

2019-11-27 15:14 UTC, closed without merging