MF1933029
idiomaticrefactoring/sehomework pull request #61
Opened 2019-11-13 13:26 UTC by ting2696

2019-11-13 14:47 UTC, idiomaticrefactoring requested changes
提交在哪里了？

2019-11-13 14:50 UTC, ting2696 commented
助教：
&nbsp; &nbsp; &nbsp; 我是fork的你的以后&nbsp; &nbsp;在我的仓库里面上传新的文件&nbsp; 然后pull request的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zzj"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 晚上10:47
收件人:&nbsp;"zjzh/sehomework"<sehomework@noreply.github.com&gt;;
抄送:&nbsp;"冰雪之吻"<493468652@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zjzh/sehomework] MF1933029 (#61)




@zjzh requested changes on this pull request.
 
提交在哪里了？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-20 14:27 UTC, zjzh commented
找到了是11月19号提交的是吗

2019-11-20 14:27 UTC, closed without merging

2019-11-20 14:29 UTC, zjzh commented on MF1933029/java/Calendar_getMinimalDaysInFirstWeek.java
> +     * class0 Calendar$class0
变量初始化

2019-11-20 14:37 UTC, zjzh commented on MF1933029/java/PrintStream_append_char.java
> +     */
class0

2019-11-20 14:38 UTC, zjzh commented on MF1933029/swift/Calendar_minimumDaysInFirstWeek.swift
> +     * class0 Calendar$class0
class0 初始化

2019-11-20 14:38 UTC, idiomaticrefactoring reviewed
good-2