MF1933072
idiomaticrefactoring/sehomework pull request #95
Opened 2019-11-20 08:05 UTC by Yudezhi

Integer,100 same
Throwable,6 same
Class,98 same
FileInputStream,26 same
LinkedList,6 same
---
本次更新添加20个新文件，其中九张截图（缺少Runtime 运行截图），一份说明文件，10份代码。
本次更新主要针对变量初始化格式进行了改进，并未相关变量添加了链接。

2019-11-21 01:29 UTC, Yudezhi commented
不知道为啥提交的关闭了。。。

2019-11-21 05:29 UTC, zjzh commented on MF1933072/java/Class_getMethods.java
> +     * ret0 Method$ret0 ="UNKNOWN" //不同时间运行出的方法顺序不同
UNKNOWN即可

2019-11-21 05:30 UTC, zjzh commented on MF1933072/java/Integer_compare_int_int.java
> +     */
class0?变量名

2019-11-21 05:30 UTC, zjzh commented on MF1933072/java/LinkedList_element.java
> +     * LinkedList<E>$class0-LinkedList<E>&E=String&link-https:https://beginnersbook.com/2013/12/linkedlist-in-java-with-example/
参看代码示例

2019-11-21 05:30 UTC, zjzh commented on MF1933072/java/Throwable_getLocalizedMessage.java
> +     * Throwable$class0-Throwable()&https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html
两个&

2019-11-21 05:41 UTC, zjzh commented on MF1933072/swift/NSError_localizedDescription.swift
> +NSError_localizedDescription.localizedDescription0()
代码不需要这么复杂查别的

2019-11-21 05:42 UTC, zjzh commented on MF1933072/swift/NSNumber_compare_NSNumber.swift
> +
变量名，下面同样问题

2019-11-21 05:42 UTC, idiomaticrefactoring reviewed
OK
想办法运行runtime
会有互评的机会可以去对方那里或者同学运行或者找助教

2019-11-21 05:54 UTC, idiomaticrefactoring requested changes
good+1

2019-11-27 07:50 UTC, Tomlk commented on MF1933072/java/FileInputStream_close.java
> +        int data = class0.read();
read() 注释？

2019-11-27 07:50 UTC, Tomlk commented on MF1933072/java/Integer_compare_int_int.java
> +     * class0 class0 = 1
class0 是Interger?这里1 是int吧?

2019-11-27 07:50 UTC, Tomlk commented on MF1933072/java/LinkedList_element.java
> +        class0.add("A");
add

2019-11-27 07:50 UTC, Tomlk commented on MF1933072/swift/Array_first.swift
> +        class0.append("A")
append

2019-11-27 07:50 UTC, Tomlk commented on MF1933072/swift/NSNumber_compare_NSNumber.swift
> +     * ret0  ret0= "orderedAscending"
猜测ordererAscending是否为一类型，因为拥有子属性rawValue？

2019-11-27 09:07 UTC, Yudezhi commented on MF1933072/java/FileInputStream_close.java
> +        int data = class0.read();
非必要

2019-11-27 09:07 UTC, Yudezhi commented on MF1933072/java/Integer_compare_int_int.java
> +     * class0 class0 = 1
嗯，已修改，但不确定是否正确

2019-11-27 09:32 UTC, Yudezhi commented
修改后重新提交，关闭当前request

2019-11-27 09:32 UTC, closed without merging