MG1933058 homework 5
idiomaticrefactoring/sehomework pull request #99
Opened 2019-11-20 09:21 UTC by wang12d

Class,150 same
String, 258 same
PrintStream, 94 same

Class里面Swift需要Objective-C Runtime，我电脑不是MACOS，所有即暂且没有代码。

2019-11-20 09:27 UTC, wang12d commented
最后一次提交只改了一个文件名字，如果看不见代码请查看倒数第二次提交，或者直接查看[Files changed](https://github.com/zjzh/sehomework/pull/99/files)，谢谢！

2019-11-21 00:40 UTC, zjzh commented on MG1933058/Java/Class_forName_String.java
> +     * ret0 ret0 = java.lang.Integer
ret0

2019-11-21 00:41 UTC, zjzh commented on MG1933058/Java/String_getChars_int_int_Array_int.java
> +      * String.length$to-String$length() & https://www.guru99.com/string-length-method-java.html
少一个&

2019-11-21 00:41 UTC, idiomaticrefactoring requested changes
good+1

2019-11-22 13:48 UTC, wang12d commented
根据反馈修改了代码，请点击[这里](https://github.com/zjzh/sehomework/pull/99/commits/ff038326630f9cda8930fb3f2dd6da4b15f74feb)查看主要的变动，或者[这里](https://github.com/zjzh/sehomework/pull/99/files)查看修改之后的所有文件。

2019-11-25 10:46 UTC, closed without merging